export default {
  SPLASH: 'Splash',
  HOME: 'Home',
  PRODUCT_DETAILS: 'ProductDetails',
  NOTIFICATIONS: 'Notifications',
  PROFILE: 'Profile',
  SEARCH: 'Search',
  WISHLIST: 'WishList',
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  CART: 'Cart',
  BOTTOM_NAVIGATION: 'BottomNavigation',
  DRAWWER_NAVIGATION: 'DrawerNavigation',
};
